In [2]:
 import numpy as np
arr= np.array([6,34,2345,7,34,78,32,57]) #1D
arr1=np.arange(1,72,2).reshape(6,6) #2D

In [4]:
print(arr)
print(arr1)

[   6   34 2345    7   34   78   32   57]
[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]
 [25 27 29 31 33 35]
 [37 39 41 43 45 47]
 [49 51 53 55 57 59]
 [61 63 65 67 69 71]]

In [10]:
print("max value is :",arr.max())
print("min value is :",arr.min())

max value is : 2345
min value is : 6

In [12]:
# To check the index position
print("Index position of minimum value",arr.argmin())
print("Index position of maximum value",arr.argmax())

Index position of minimum value 0
Index position of maximum value 2

In [13]:
arr1

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45, 47],
       [49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71]])

In [ ]:
# here the problem is while using the argmax where it count position of the 2d array as 1d
arr1.argmax()

In [ ]:
#axis

In [18]:
arr2=np.arange(1,13).reshape(4,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
#Fetch 8 from arr2
arr2[2][1]

8

In [21]:
#fetch 11
arr2[3][1]

11

In [25]:
# fetch 5,6
arr2[1][1:]

array([5, 6])

In [28]:
# fetching 5,6,8,9
arr2[1:3,1:]

array([[5, 6],
       [8, 9]])

In [30]:
# check this please arr2[1:3][1:]

### Filtering

In [33]:
arr = np.array([6,34,2345,7,34,78,32,57])
print(np.where(arr > 50)) # gives back all the index where the value is greater than 50
print(arr[arr > 50]) # here give the exact value

(array([2, 5, 7], dtype=int64),)
[2345   78   57]

In [35]:
a=np.ones((6,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
for i in range(len(a)):
    a[i]=i

In [37]:
a

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.]])

## Pandas

In [38]:
import pandas as pd
ser = pd.Series([34,65,24,654,67,86,443,234,5])
ser

0     34
1     65
2     24
3    654
4     67
5     86
6    443
7    234
8      5
dtype: int64

In [40]:
print(ser.shape)
print(ser.ndim)
print(ser.size)
print(ser.dtype)
print(ser.values)

(9,)
1
9
int64
[ 34  65  24 654  67  86 443 234   5]

In [43]:
ser1 = pd.Series({'a':4,'b':7,'c':6,'d':78,'e':'apple'})
ser1

a        4
b        7
c        6
d       78
e    apple
dtype: object

In [47]:
# Indexing of series
# get 7 from the above series
print(ser1[1])
print(ser1['b'])

7
7

C:\Users\prath\AppData\Local\Temp\ipykernel_19776\1411567278.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser1[1])

## DataFrame

In [55]:
a= [[2,3],['apple','ball'],['cat','god']]
df=pd.DataFrame(a, columns = ['cl1', 'cl2'], index=['as', 'sa', 'bs']) # the index value should not be changed [recommended]
df

      cl1   cl2
as      2     3
sa  apple  ball
bs    cat   god

In [57]:
b = {'a':[1,2,3],'b':[4,5,6]}
df1=pd.DataFrame(b)
df1

   a  b
0  1  4
1  2  5
2  3  6